================ CONF START =================
[Interface]
PrivateKey = iFn2xex/QPYk5mbWrJCjzU6jVFiCvp/DC4kVkcnflF0=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = MpF4or3NByUJnxUIvOgiW97QtbnWUjVSzzKyvwO1HiI=
AllowedIPs = 0.0.0.0/0
Endpoint = :51820
================= CONF END ==================
