[Interface]
PrivateKey = SJ6V0gVNFkDeRBW9xSiz66m5HveLx6xNgiEF7+j8DXQ=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
PublicKey = A96HvoPydhf4v75//ZT/kSzV3V6gsEGSA2V8Y2hgOw0=
AllowedIPs = 0.0.0.0/0
Endpoint = :51820
================= CONF END ==================
